//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace SynchApp {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Configuration {
        
        private ConfigurationOptions optionsField;
        
        private ConfigurationBackup[] backupsField;
        
        /// <remarks/>
        public ConfigurationOptions Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Backup", IsNullable=false)]
        public ConfigurationBackup[] Backups {
            get {
                return this.backupsField;
            }
            set {
                this.backupsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ConfigurationOptions {
        
        private bool excludeHiddenField;
        
        private bool excludeIdenticalField;
        
        private bool analyseOnlyField;
        
        private bool deleteDirectoriesField;
        
        private bool deleteFilesField;
        
        private bool topLevelDirectoriesField;
        
        private bool useRegexField;
        
        /// <remarks/>
        public bool excludeHidden {
            get {
                return this.excludeHiddenField;
            }
            set {
                this.excludeHiddenField = value;
            }
        }
        
        /// <remarks/>
        public bool excludeIdentical {
            get {
                return this.excludeIdenticalField;
            }
            set {
                this.excludeIdenticalField = value;
            }
        }
        
        /// <remarks/>
        public bool analyseOnly {
            get {
                return this.analyseOnlyField;
            }
            set {
                this.analyseOnlyField = value;
            }
        }
        
        /// <remarks/>
        public bool deleteDirectories {
            get {
                return this.deleteDirectoriesField;
            }
            set {
                this.deleteDirectoriesField = value;
            }
        }
        
        /// <remarks/>
        public bool deleteFiles {
            get {
                return this.deleteFilesField;
            }
            set {
                this.deleteFilesField = value;
            }
        }
        
        /// <remarks/>
        public bool topLevelDirectories {
            get {
                return this.topLevelDirectoriesField;
            }
            set {
                this.topLevelDirectoriesField = value;
            }
        }
        
        /// <remarks/>
        public bool useRegex {
            get {
                return this.useRegexField;
            }
            set {
                this.useRegexField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ConfigurationBackup {
        
        private string sourceField;
        
        private string destinationField;
        
        private ConfigurationBackupDirectoryExcludes directoryExcludesField;
        
        private ConfigurationBackupDirectoryIncludes directoryIncludesField;
        
        private string nameField;
        
        /// <remarks/>
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public ConfigurationBackupDirectoryExcludes directoryExcludes {
            get {
                return this.directoryExcludesField;
            }
            set {
                this.directoryExcludesField = value;
            }
        }
        
        /// <remarks/>
        public ConfigurationBackupDirectoryIncludes directoryIncludes {
            get {
                return this.directoryIncludesField;
            }
            set {
                this.directoryIncludesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ConfigurationBackupDirectoryExcludes {
        
        private string[] directoryExcludeField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("directoryExclude")]
        public string[] directoryExclude {
            get {
                return this.directoryExcludeField;
            }
            set {
                this.directoryExcludeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ConfigurationBackupDirectoryIncludes {
        
        private string[] directoryIncludeField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("directoryInclude")]
        public string[] directoryInclude {
            get {
                return this.directoryIncludeField;
            }
            set {
                this.directoryIncludeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
}
