//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace SynchApp {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class directoryFilter {
        
        private bool fullPathField;
        
        private bool fullPathFieldSpecified;
        
        private bool topLevelOnlyField;
        
        private bool topLevelOnlyFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool fullPath {
            get {
                return this.fullPathField;
            }
            set {
                this.fullPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fullPathSpecified {
            get {
                return this.fullPathFieldSpecified;
            }
            set {
                this.fullPathFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool topLevelOnly {
            get {
                return this.topLevelOnlyField;
            }
            set {
                this.topLevelOnlyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool topLevelOnlySpecified {
            get {
                return this.topLevelOnlyFieldSpecified;
            }
            set {
                this.topLevelOnlyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class directoryExcludes {
        
        private directoryFilter[] directoryFilterField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("directoryFilter")]
        public directoryFilter[] directoryFilter {
            get {
                return this.directoryFilterField;
            }
            set {
                this.directoryFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class directoryIncludes {
        
        private directoryFilter[] directoryFilterField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("directoryFilter")]
        public directoryFilter[] directoryFilter {
            get {
                return this.directoryFilterField;
            }
            set {
                this.directoryFilterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Backup {
        
        private string sourceField;
        
        private string destinationField;
        
        private directoryExcludes directoryExcludesField;
        
        private directoryIncludes directoryIncludesField;
        
        private string nameField;
        
        /// <remarks/>
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
            }
        }
        
        /// <remarks/>
        public directoryExcludes directoryExcludes {
            get {
                return this.directoryExcludesField;
            }
            set {
                this.directoryExcludesField = value;
            }
        }
        
        /// <remarks/>
        public directoryIncludes directoryIncludes {
            get {
                return this.directoryIncludesField;
            }
            set {
                this.directoryIncludesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Options {
        
        private bool excludeHiddenField;
        
        private bool excludeIdenticalField;
        
        private bool analyseOnlyField;
        
        private bool deleteDirectoriesField;
        
        private bool deleteFilesField;
        
        private bool useRegexField;
        
        /// <remarks/>
        public bool excludeHidden {
            get {
                return this.excludeHiddenField;
            }
            set {
                this.excludeHiddenField = value;
            }
        }
        
        /// <remarks/>
        public bool excludeIdentical {
            get {
                return this.excludeIdenticalField;
            }
            set {
                this.excludeIdenticalField = value;
            }
        }
        
        /// <remarks/>
        public bool analyseOnly {
            get {
                return this.analyseOnlyField;
            }
            set {
                this.analyseOnlyField = value;
            }
        }
        
        /// <remarks/>
        public bool deleteDirectories {
            get {
                return this.deleteDirectoriesField;
            }
            set {
                this.deleteDirectoriesField = value;
            }
        }
        
        /// <remarks/>
        public bool deleteFiles {
            get {
                return this.deleteFilesField;
            }
            set {
                this.deleteFilesField = value;
            }
        }
        
        /// <remarks/>
        public bool useRegex {
            get {
                return this.useRegexField;
            }
            set {
                this.useRegexField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Backups {
        
        private Backup[] backupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Backup")]
        public Backup[] Backup {
            get {
                return this.backupField;
            }
            set {
                this.backupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Configuration {
        
        private Options optionsField;
        
        private Backup[] backupsField;
        
        /// <remarks/>
        public Options Options {
            get {
                return this.optionsField;
            }
            set {
                this.optionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Backup", IsNullable=false)]
        public Backup[] Backups {
            get {
                return this.backupsField;
            }
            set {
                this.backupsField = value;
            }
        }
    }
}
